YES                 = 'Да'
NO                  = 'Нет'
COMMAND_SHOW        = '/show'
GO_TO_MAIN_MENU     = 'К главному меню'
SEND_LOCATION       = 'Отправить местоположение'
RECEIVING_INFO      = 'Собираю информацию...'
MISUNDERSTANDING    = 'Не понимаю команды. Напишите /help'
COUNTING_DISTANCE   = 'Считаю дистанцию до ближайшего офиса...'
